# Generated by Django 4.1.3 on 2022-11-30 20:39


from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "assigned" : "A task that has been assigned to a user",
        "in-progress" : "A task that is being worked on",
        "complete" : "A task that is complete",
        "archived" : "A task that has been archived"
    }
    Status = apps.get_model("tasks", "Status")

    for name, desc in entries.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_status'),
    ]

    operations = [migrations.RunPython(populate_status)]
