# Generated by Django 4.1.3 on 2022-12-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
